spring:
  security:
    user:
      name: ${STAGE_BIKUBE_USERNAME}
      password: ${STAGE_BIKUBE_PASSWORD}

security:
  enabled: true

axiell:
  url: ${COLLECTIONS_PATH_STAGE}
  username: ${COLLECTIONS_USERNAME_STAGE}
  password: ${COLLECTIONS_PASSWORD_STAGE}
