package no.nb.bikube.api.newspaper.service

import no.nb.bikube.api.newspaper.model.IdResponse
import no.nb.bikube.api.newspaper.model.ParsedIdResponse
import no.nb.bikube.api.newspaper.model.toParsedIdResponse
import org.springframework.beans.factory.annotation.Value
import org.springframework.stereotype.Service
import org.springframework.web.reactive.function.client.WebClient
import reactor.core.publisher.Mono

// TODO: After migration the id's fetched here are generated by Collections
// Entirely temporary service while we migrate. Will be removed when collections does the id generation for us.
@Service
class MaxitService(
    @Value("\${maxit.url}") private val maxitUrl: String
) {
    private val webClient: WebClient by lazy {
        WebClient.builder()
            .baseUrl(maxitUrl)
            .build()
    }

    fun getUniqueIds(): Mono<ParsedIdResponse> {
        return webClient.get()
            .uri("/id/priref-and-objectnumber")
            .retrieve()
            .bodyToMono(IdResponse::class.java)
            .onErrorMap {
                RuntimeException("Failed to get unique id from Maxit API", it)
            }
            .map {
                it.toParsedIdResponse()
            }
    }
}
