package no.nb.bikube.newspaper.service

import no.nb.bikube.newspaper.model.IdResponse
import no.nb.bikube.newspaper.model.ParsedIdResponse
import no.nb.bikube.newspaper.model.toParsedIdResponse
import org.springframework.beans.factory.annotation.Value
import org.springframework.stereotype.Service
import org.springframework.web.reactive.function.client.WebClient

// TODO: After migration the id's fetched here are generated by Collections
// Entirely temporary service while we migrate. Will be removed when collections does the id generation for us.
@Service
class MaxitService(
    @Value("\${maxit.base-url}") private val maxitBaseUrl: String
) {
    private val webClient: WebClient by lazy {
        WebClient.builder()
            .baseUrl(maxitBaseUrl)
            .build()
    }

    fun getUniqueIds(): ParsedIdResponse {
        val id = webClient.get()
            .uri("/id/priref-and-objectnumber")
            .retrieve()
            .bodyToMono(IdResponse::class.java)
            .block() ?: throw RuntimeException("Failed to get unique id from Maxit API")
        return id.toParsedIdResponse()
    }
}