package no.nb.bikube.api.newspaper.service

import no.nb.bikube.api.newspaper.model.IdResponse
import no.nb.bikube.api.newspaper.model.ParsedIdResponse
import no.nb.bikube.api.newspaper.model.toParsedIdResponse
import org.springframework.beans.factory.annotation.Value
import org.springframework.stereotype.Service
import org.springframework.web.reactive.function.client.WebClient
import org.springframework.web.reactive.function.client.bodyToMono
import reactor.core.publisher.Mono

// TODO: After migration the id's fetched here are generated by Collections
// Entirely temporary service while we migrate. Will be removed when collections does the id generation for us.
@Service
class MaxitService(
    @Value("\${maxit.url}") private val maxitUrl: String,
    @Value("\${featureflag.maxit-id:true}") private val maxitIdEnabled: Boolean,
) {
    private val webClient: WebClient by lazy {
        WebClient.builder()
            .baseUrl(maxitUrl)
            .build()
    }

    fun getUniqueIds(): Mono<ParsedIdResponse> {
        return (if(maxitIdEnabled) {
            webClient.get()
                .uri("/id/priref-and-objectnumber")
                .retrieve()
                .bodyToMono<IdResponse>()
                .onErrorMap {
                    RuntimeException("Failed to get unique id from Maxit API", it)
                }
                .map {
                    it.toParsedIdResponse()
                }
        } else {
            ParsedIdResponse(null, null)
        }) as Mono<ParsedIdResponse>
    }
}
